aws-solutions-library-samples/guidance-for-processing-overhead-imagery-on-aws

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/support_question.yml
.github/PULL_REQUEST_TEMPLATE.md

**Description of changes:** Created a set of templates for PR and Issues

Initial PR / Issue templates

---

.github/workflows/osml_update_submodules.yml

- Automatically update submodules when the changes are merged into either main or dev branch in `osml-*` repos
- See this PR: https://github.com/RanbirAulakh/guidance-for-overhead-imagery-inference-on-aws/pull/8

Add update submodule workflow

---

package-lock.json

Merging main into dev for security patching.

fix: merge main to dev

---

package.json

Typo in aircraft integ test npm command

fixing package.json command for aircraft integ test

---

.github/workflows/osml_build_test.yml

- There's a typo in the workflow that is using the different CODEBUILD project. However, it does not impact with the current implementation before this PR. It makes the organizing bit easier. 
- Validate the `Checks` tab of this PR succeeded.

fix: Update CODEBUILD project name

---

README.md

- Include a short section about the memorysize error in the readme.md
- n/a

fix: Add MemorySize error in README.md

---

.github/copyright.yaml
.pre-commit-config.yaml
README.md
bin/app.ts
bin/deploy-model-runner.ts
bin/deploy-roles.ts
bin/deploy-tile-server.ts
bin/deploy-vpc.ts
lib/osml-stacks/model_runner/mr-autoscaling.ts
lib/osml-stacks/model_runner/mr-container.ts
lib/osml-stacks/model_runner/mr-dataplane.ts
lib/osml-stacks/model_runner/mr-endpoints.ts
lib/osml-stacks/model_runner/mr-imagery.ts
lib/osml-stacks/model_runner/mr-model-container.ts
lib/osml-stacks/model_runner/mr-sync.ts
lib/osml-stacks/osml-monitoring.ts
lib/osml-stacks/osml-roles.ts
lib/osml-stacks/osml-vpc.ts
lib/osml-stacks/tile_server/ts-container.ts
lib/osml-stacks/tile_server/ts-dataplane.ts

Updating copyright and adding pre-commit hooks to manage it going forward.

chore: update copyright

---

.github/codebuild/cdk-nag.yml
.github/workflows/osml_build_test.yml
.github/workflows/osml_cdk_nag.yml
bin/app.ts

This is WIP to verify the github action works
- Add CDK-Nag workflow to produce the outputs

build: produce cdk nag result

---

.github/codebuild/cdk-nag.yml
.github/workflows/osml_cdk_nag.yml

- Update S3 bucket name to be unique for each account

build: update cdk nag bucket name

---

README.md
scripts/ec2_bootstrap.sh

Created an EC2 bootstrap script to automatically install all dependencies onto a fresh EC2 instance to demo OSML
Ran integ:aircraft successfully in commercial AWS region (us-west-2) with 22.04 Ubuntu, t3.medium, 50 GiB root volume

Created EC2 Bootstrap script

---

.github/codebuild/build.yml
.github/codebuild/destroy.yml
.github/workflows/osml_build_test.yml
package-lock.json

- Update if/else statement in bash. `-eq` is not the same as `==`
- Update package-lock.json file by running `npm i`
- Check actions tab

chore (dep): update package.json & github workflows

---

.github/workflows/osml_cdk_nag.yml
README.md
bin/app.ts
bin/deploy-data-catalog.ts
lib/accounts/README.md
lib/accounts/target_account_template.json
lib/osml-stacks/data-catalog/dc-container.ts
lib/osml-stacks/data-catalog/dc-dataplane.ts
scripts/dev_destroy.sh

- Integrate STAC-Catalog feature
- Check `Checks` tab since this [PR](https://github.com/aws-solutions-library-samples/osml-cdk-constructs/pull/114) has been merged in

feat: integrate STAC-Catalog feature

---

README.md

- Update README.md relating to auth configuration changes. 
- Check `Checks` tab
- Do not merge until new version of `osml-cdk-constructs` released that contains this changes
- https://github.com/aws-solutions-library-samples/osml-cdk-constructs/pull/123

chore: README updates relating to auth configuration

---

scripts/ec2_bootstrap_al2.sh

* Fixing bootstrap scripts to run correctly on their corresponding operating systems.
Created fresh EC2 instances for both Ubuntu and AL2, ran scripts, validated installations. 

chore: fix bootstrap scripts

---

bin/app.ts
bin/deploy-data-catalog.ts
bin/deploy-data-intake.ts
bin/deploy-model-runner.ts
bin/deploy-tile-server.ts
bin/deploy-vpc.ts
lib/osml-stacks/data-catalog/dc-dataplane.ts
lib/osml-stacks/data-catalog/dc-ingest-container.ts
lib/osml-stacks/data-catalog/dc-stac-container.ts
lib/osml-stacks/data_intake/di-container.ts
lib/osml-stacks/data_intake/di-dataplane.ts
lib/osml-stacks/model_runner/mr-container.ts
lib/osml-stacks/model_runner/mr-endpoints.ts
lib/osml-stacks/osml-roles.ts
lib/osml-stacks/tile_server/testing/ts-test-runner.ts
lib/osml-stacks/tile_server/ts-container.ts
package-lock.json
package.json

This change implements the data ingest components and is aimed at enhancing the functionality of our current geospatial data processing capabilities. By leveraging STAC, we can standardize the way geospatial data is indexed and accessed, improving interoperability and scalability of our data resources. It allows for the deployment of new assets and enhancement of existing ones including the data catalog ingest, API, and intake components through our CDK constructs.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

feat: implement data ingest

---

package-lock.json
package.json
scripts/model_runner_integ.sh
scripts/tile_server_integ.sh

- There's no way to view what is happening behind the scene of the integration tests. It does not fully show the errors if it occurred.

fix: show integration test results

---

scripts/tile_server_integ.sh

Displays test results in failure case in a more readable way.

test: updating ts integ test console output for readability

---

package.json

- Update osml-cdk-constructs version

chore: update osml-cdk-constructs

---

.github/cdk.context.github.json
README.md
documentation/deployment/README.md
package-lock.json
package.json

- Update `osml-cdk-constructs` to `2.0.5`
- Update `.github/cdk.context.github.json` to eliminate `BUILD_FROM_SOURCE`
- Remove `npm run setup` since that does not exist in `package.json` in README
- Update indentations in deployment README
- Check `Checks` tab

chore: update osml-cdk-constructs and update READMEs

---

package-lock.json
package.json

- Update `osml-cdk-constructs` to 2.0.6
- Check `Checks` tab

build: update osml-cdk-constructs version
